server:
  port: 11949

agent:
  catalog:
    external-dir: ${AGENT_EXTERNAL_DIR:agents}
  auth:
    enabled: true
    local-public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvxdDm9dyu1Ov8sbuGToW
      K306NnpMc04hmMBV3eTgRDnCes4UETn5FaHGChPwrIZ5cSwrjitg1CdJWdo8wHAD
      Xw8x+QSO6lJz/X6Xy9a4+j3Bj3PRwflUSWvEo4bJ6BBAzHwiAbprA0pyX5xAGZfm
      jv9aD+PG241mxRLcbBsnRyUul6x+ojoQTDX71+wzuvmzjlglS8I+izoQaGoOyo2Z
      YA3uWawebNEcUEBKOYNv2VAYUuT+qlJ4vuMqi0IT9cdcxIVu4Uyc2aE3AFn2i4Bl
      g8O+YHSPJ17+jckUo93NM/aVcNm2u6LXZD1J4akGPRefz9HkBLZ9GJY3kVm9mMyZ
      7QIDAQAB
      -----END PUBLIC KEY-----
  chat-image-token:
    secret: ${CHAT_IMAGE_TOKEN_SECRET:ap_chat_image}
    ttl-seconds: ${CHAT_IMAGE_TOKEN_TTL_SECONDS:86400}
  providers:
    bailian:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${BAILIAN_API_KEY:sk-630760c3585e4182b4687456093e0e00}
      model: ${BAILIAN_MODEL:qwen3-max}
    siliconflow:
      base-url: https://api.siliconflow.cn
      api-key: ${SILICONFLOW_API_KEY:sk-hnhnkwdtefarlmwdjvryfyuaixzayjcirggykxvqqagrkokl}
      model: ${SILICONFLOW_MODEL:deepseek-ai/DeepSeek-V3.2}
    babelark:
      base-url: https://babelark.com/
      api-key: ${BABELARK_API_KEY:sk-g5y344NHN9eBktWX0EpfLrAiou7JIZZAVjJ8BmrOXlf7PFiK}
      model: ${BABELARK_MODEL:GLM-5}
  tools:
    bash:
      working-directory: /Users/linlay-macmini
      allowed-paths:
        - /Users/linlay-macmini/Server
        - /Users/linlay-macmini/Project
      allowed-commands: ls,pwd,cat,head,tail,less,wc,cut,sort,uniq,tr,sed,awk,grep,rg,find,xargs,printf,echo,env,which,dirname,basename,stat,realpath,readlink,git,mvn,java,javac,jar,gradle,make,cmake,node,npm,npx,pnpm,yarn,python,python3,pip,pip3,pytest,go,gofmt,cargo,rustc,docker,curl,wget,tar,unzip,zip,gzip,gunzip,touch,mkdir,cp,mv,rm,tee,ln,ps,top,free,df,du,lsof,netstat,ss,kill,pkill,jq
      path-checked-commands: ls,cat,head,tail,less,wc,cut,sort,uniq,tr,sed,awk,grep,rg,find,git,tar,unzip,zip,gzip,gunzip,touch,mkdir,cp,mv,rm,tee,ln,stat,realpath,readlink
      shell-features-enabled: true
      shell-executable: bash
      shell-timeout-ms: 10000
      max-command-chars: 16000
